openapi: 3.0.3
info:
  title: Data Streaming - OpenAPI
  description: |
    The Data Streaming API allows you to manage your existing data streamings and templates.|
    Data Streaming allows you to feed your stream processing, SIEM, and big data platforms with the event logs from your applications on Azion in real time.

  license:
    name: MIT
    url: https://github.com/aziontech/azionapi-openapi/blob/main/LICENSE.md
  version: 1.0.0
externalDocs:
  description: See the documentation of Data Streaming for more information.
  url: https://www.azion.com/en/documentation/products/data-streaming/
servers:
  - description: Production
    url: https://api.azionapi.net
security:
  - tokenAuth: []
tags:
  - name: Data Streaming
    description: List all data streamings
paths:
  /data_streaming/streamings:
    get:
      tags:
        - Data Streaming
      summary: List all exist data streamings
      description: List all exist data streamings
      operationId: ListDataStreamings
      
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataStreamingResponseWithResults' 
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '429':
          description: Rate Limit
        '500':
          description: Internal Server Error
  
  /data_streaming/domains:
    get:
      tags:
        - Data streaming
      summary: List a data streaming by domain's name
      description: List a data streaming info
      operationId: ListDataStreaming
      parameters: 
      - in: query
        name: name
        description: Domain's name in data streaming 
        required: false
        schema:
          type: string
      - in: query
        name: streaming_id
        required: false
        schema:
          format: int64
          type: integer
      - in: query
        name: selected
        required: false
        schema:
          type: boolean
    
      responses:
        '200':
          description: Successful operation
            
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '429':
          description: Rate Limit
        '500':
          description: Internal Server Error

components:
  schemas:
    DataStreamingResponseWithResults:
      type: object
      properties:
        results:
            type: array
            items:
              anyOf:
                - $ref: '#/components/schemas/DataStreamingResponseGetResultTypeDatadogDTS'
                - $ref: '#/components/schemas/DataStreamingResponseGetResultTypeKafka'
                - $ref: '#/components/schemas/DataStreamingResponseGetResultTypeStandard'
                - $ref: '#/components/schemas/DataStreamingResponseGetResultTypeCustom'
        schema_version: 
          type: number
   
    DataStreamingResponseGetResultTypeDatadogDTS:
      type: object
      properties:
        id: 
          type: number
          format: integer
        name:
          type: string
        template_id: 
          type: number
          format: integer
        data_source:
           type: string
        active:
          type: boolean
        endpoint:
            $ref: '#/components/schemas/DataStreamingEndpointTypeDatadogDTS'
        all_domains:
          type: boolean

    DataStreamingEndpointTypeDatadogDTS:
      type: object
      properties:
        endpoint_type:
          type: string
        url:
          type: string
        api_key:
          type: string
  
  
    DataStreamingResponseGetResultTypeKafka:
      type: object
      properties:
        id: 
          type: number
          format: integer
        name:
          type: string
        template_id: 
          type: number
          format: integer
        data_source:
           type: string
        active:
          type: boolean
        endpoint:
            $ref: '#/components/schemas/DataStreamingEndpointTypeKafka'
        all_domains:
          type: boolean
          
    DataStreamingEndpointTypeKafka:
      type: object
      properties:
        endpoint_type:
          type: string
        use_tls:
          type: boolean
        kafka_topic:
          type: string
        bootstrap_servers:
          type: string
          
          
    DataStreamingResponseGetResultTypeStandard:
      type: object
      properties:
        id: 
          type: number
          format: integer
        name:
          type: string
        template_id: 
          type: number
          format: integer
        data_source:
           type: string
        active:
          type: boolean
        endpoint:
            $ref: '#/components/schemas/DataStreamingEndpointTypeStandard'
        all_domains:
          type: boolean
          
    DataStreamingEndpointTypeStandard:
      type: object
      properties:
        endpoint_type:
          type: string
        url:
          type: string
        log_line_separator:
          type: string
        payload_format:
          type: string
        max_size:
          type: number
        headers:
          $ref: '#/components/schemas/DataStreamingEndpointTypeStandardHeadersExample'
          
    DataStreamingEndpointTypeStandardHeadersExample:
      type: object
      properties:
        header-name-1:
          type: string
          nullable: true
        header-name-2:
          type: string
          nullable: true
        header-name-3:
          type: string
          nullable: true
          
          
    DataStreamingResponseGetResultTypeCustom:
      type: object
      properties:
        id: 
          type: number
          format: integer
        name:
          type: string
        data_source:
           type: string
        active:
          type: boolean
        endpoint:
            $ref: '#/components/schemas/DataStreamingEndpointTypeKafka'
        all_domains:
          type: boolean
        template_model:
          type: string
          
  
    DataStreamingsDomain:
      type: object
      properties:
        domain_id:
          type: number
          format: integer
        name:
          type: string
        selected:
          type: number
          format: integer
          nullable: true

  securitySchemes:
    tokenAuth:
      type: apiKey
      name: Authorization
      in: header
      description: |
        You must inform a token to auth.
        Usage format: `Token <TOKEN>`
        