
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test_job:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:18.04
    steps:
      - name: Setup Env
        run: apt-get update && apt-get install -y git nodejs npm

      - name: Setting GIT
        run: git config --global url."https://${{ secrets.GLOBAL_TOKEN }}:x-oauth-basic@github.com/aziontech".insteadOf "https://github.com/aziontech"

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: OpenAPI Lint Checks
        uses: trybeapp/redocly-openapi-cli-github-action@v0.0.1
        with:
          args: 'lint *.yaml'

      - name: Install openapi-linter 
        run: |
          npm i -g @superfaceai/openapi-linter

      #get all .yaml files which were added/modified
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files: |
            **/*.yaml
        
      #run openapi-linter for these files 
      - name: Run linter for all changed files
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "running linter for: $file"
            oal lint $file -f yaml
          done

