
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  DIR: $(pwd)

jobs:
  test_job:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:18.04
    steps:
      - name: test env
        run: echo $DIR
      - name: Setup Env
        run: apt-get update && apt-get install -y git

      - name: Setting GIT
        run: git config --global url."https://${{ secrets.GLOBAL_TOKEN }}:x-oauth-basic@github.com/aziontech".insteadOf "https://github.com/aziontech"

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: OpenAPI Lint Checks
        uses: trybeapp/redocly-openapi-cli-github-action@v0.0.1
        with:
          args: 'lint *.yaml'

