name: Generate

on:
  push:
    branches: [ poc-automation ]
  pull_request:
    branches: [ poc-automation ]

jobs:
  test_job:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04
    steps:
      - name: Setup Env
        run: apt-get update && apt-get install -y npm curl git

      - name: Git config
        run: git config --global --add safe.directory /__w/azionapi-openapi/azionapi-openapi


      - uses: actions/setup-node@v3
        with:
          node-version: 14

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: install openapi-generator
        run: npm install @openapitools/openapi-generator-cli -g

      - name: Setting GIT
        run: git config --global url."https://${{ secrets.GLOBAL_TOKEN }}:x-oauth-basic@github.com/aziontech".insteadOf "https://github.com/aziontech"


      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      # - name: Checkout
      #   uses: actions/checkout@v3
      #   with:
      #     repository: aziontech/azionapi-go-sdk
      #     path: './gosdk'

      #get all .yaml files which were added/modified
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files: |
            **/*.yaml

      - name: Run openapi-generator for changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            removed=$(echo ${file} | cut -d. -f1);
            npx @openapitools/openapi-generator-cli generate -i $file -g go -o ./azionapi-go-sdk/${removed} --package-name ${removed};\
          done
      
      - name: push changes
        run: |
          git clone https://${{ secrets.REPO_ACCESS_TOKEN }}@github.com/aziontech/azionapi-go-sdk.git
          cd ./azionapi-go-sdk/edgenode
          git config --global user.email "patrick.menoti@azion.com"
          git config --global user.name "PatrickMenoti"
          git add .
          git commit -m "Auto-Generated SDK"
          git push -f