name: Generate

on:
  push:
    branches: [ poc-automation ]
  pull_request:
    branches: [ poc-automation ]

jobs:
  test_job:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04
    steps:
      - name: Setup Env
        run: apt-get update && apt-get install -y npm curl git

      - name: install gh changed-files
        run: |
          type -p curl >/dev/null || (apt update && apt install curl -y)
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
          && chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
          && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
          && apt update \
          && apt install gh -y

      - name: Git config
        run: git config --global --add safe.directory /__w/azionapi-openapi/azionapi-openapi


      - uses: actions/setup-node@v3
        with:
          node-version: 14

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: install openapi-generator
        run: npm install @openapitools/openapi-generator-cli -g

      - name: Setting GIT
        run: git config --global url."https://${{ secrets.GLOBAL_TOKEN }}:x-oauth-basic@github.com/aziontech".insteadOf "https://github.com/aziontech"

      # - name: git glone
      #   run: git clone https://${{ secrets.REPO_ACCESS_TOKEN }}@github.com/aziontech/azionapi-go-sdk.git

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Checkout go repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          repository: aziontech/azionapi-go-sdk
          path: 'go'
          token: ${{ secrets.REPO_ACCESS_TOKEN }}

      - name: Checkout php repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          repository: aziontech/azionapi-php-sdk
          path: 'php'
          token: ${{ secrets.REPO_ACCESS_TOKEN }}

      #get all .yaml files which were added/modified
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files: |
            **/*.yaml

      - name: Run openapi-generator for changed files and push them to github
        run: |
          git config --global user.email "patrick.menoti@gmail.com"
          git config --global user.name "PatrickMenoti"
          while read type; \
          do\
            for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
              removed=$(echo ${file} | cut -d. -f1);
              npx @openapitools/openapi-generator-cli generate -i $file -g ${type} -o ./${type}/${removed} --package-name ${removed};\
              cd ${type}
              git checkout -b generated-sdk
              git add .
              git commit -m "Auto-Generated SDK"
              git push origin generated-sdk
              gh pr create --body "Auto-generated SDK" --title "Auto-generated SDK"
              cd ..
            done
          done < TYPES
        env:
          GH_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
      
      # - name: push changes
      #   run: |
      #     cd ./gosdk/edgenode
      #     git config user.email "patrick.menoti@gmail.com"
      #     git config user.name "PatrickMenoti"
      #     git checkout -b generated-sdk
      #     git add .
      #     git commit -m "Auto-Generated SDK"
      #     git push origin generated-sdk
      #     gh pr create --body "Auto-generated SDK" --title "Auto-generated SDK"
      #   env:
      #     GH_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}