name: Generate

on:
  push:
    branches: [ main ]

jobs:
  generate_job:
    name: generate SDK and push to repositories
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04
    strategy:
      matrix:
        types: [ "go", "php", "csharp", "typescript-node", "java", "rust", "python", "javascript" ]
    steps:
      - name: Setup Env
        run: apt-get update && apt-get install -y npm curl git
        shell: bash

      - name: install gh cli
        run: |
          type -p curl >/dev/null || (apt update && apt install curl -y)
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
          && chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
          && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
          && apt update \
          && apt install gh -y
        shell: bash

      - name: Git config
        run: git config --global --add safe.directory /__w/azionapi-openapi/azionapi-openapi
        shell: bash


      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: install openapi-generator
        run: npm install @openapitools/openapi-generator-cli -g
        shell: bash

      - name: Setting GIT
        run: git config --global url."https://${{ secrets.GLOBAL_TOKEN }}:x-oauth-basic@github.com/aziontech".insteadOf "https://github.com/aziontech"
        shell: bash

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Setup SSH for SDK repo
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets['REPO_ACCESS_TOKEN_'+matrix.types] }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
        shell: bash
      
      - name: Checkout SDK repo
        run: git clone git@github.com:aziontech/azionapi-${{ matrix.types }}-sdk.git ${{ matrix.types }}
        shell: bash

      # get all .yaml files which were added/modified
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files: |
            **/*.yaml

      - name: Run openapi-generator for changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            removed=$(echo ${file} | cut -d. -f1);
            npx @openapitools/openapi-generator-cli generate -i $file -g ${{ matrix.types }} -o ./${{ matrix.types }}/${removed} --package-name ${removed};\
            echo 'go.mod' >> ./${{ matrix.types }}/${removed}/.gitignore
            echo 'go.sum' >> ./${{ matrix.types }}/${removed}/.gitignore
          done
        shell: bash

      - name: push changes
        run: |
          cd ${{ matrix.types }}
          git config user.name 'GitHubActionBot'
          git config user.email 'github-action@users.noreply.github.com'
          git add .
          git commit -m "Auto-Generated SDK"
          git push origin main
        shell: bash
      
